name: lab-2 ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.0
          cache: true
          opam-depext: true

      - name: Install dependencies
        run: opam install . --deps-only -y

      - name: Check formatting
        run: |
          find src test -type f \( -name "*.ml" -o -name "*.mli" \) \
            | xargs ocamlformat --enable-outside-detected-project --check

      - name: Build
        run: dune build

      - name: Run tests
        run: |
          dune build @runtest      
          dune exec ./test/tests.exe
          dune exec ./test/property_tests.exe
