name: lab-2 ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OCaml and OPAM
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5.3.0' 

      - name: Install dependencies
        run: |
          opam update
          opam switch create my-switch 5.3.0 --deps-only
          eval $(opam env)

      - name: Install ocamlformat 0.27.0
        run: |
          opam install ocamlformat.0.27.0

      - name: Check code formatting
        run: |
          opam exec -- dune exec -- ocamlformat --check

      - name: Build project
        run: |
          dune build

      - name: Run tests
        run: |
          dune runtest
          opam exec -- dune exec -- ./test/tests.exe

      - name: Run property-based tests
        run: |
          opam exec -- dune exec -- ./test/property_tests.exe
